"""
Unit tests for the SRT parser and the encoding fallback chain (step 2.2 / 2.3).

Runs everywhere: no database, no network. Fixtures are generated by
``tests/data/make_fixtures.py``; their expected results live in the same table,
so a fixture and its assertion can never drift apart.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

from app.subtitle_parser import (
    DEFAULT_CUE_DURATION_MS,
    FALLBACK_ENCODINGS,
    SubtitleFileError,
    SubtitleParserService,
    _srt_time_to_ms,
)

pytestmark = pytest.mark.unit

DATA_DIR = Path(__file__).resolve().parent / "data"


def _load_manifest():
    """Import tests/data/make_fixtures.py by path (it is not an installed package).

    See ``tests/conftest.py``: the module has to be in ``sys.modules`` while it
    executes, otherwise the postponed annotations of its dataclasses do not resolve.
    """
    spec = importlib.util.spec_from_file_location("make_fixtures", DATA_DIR / "make_fixtures.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(spec.name, None)
    return module


MANIFEST = _load_manifest()
MANIFEST.write_fixtures(DATA_DIR)  # idempotent: regenerates the .srt files from the table
SPECS = {fixture.name: fixture for fixture in MANIFEST.FIXTURES}


def _fixture(name: str) -> Path:
    return DATA_DIR / name


def _cue(index: int, text: str, start_s: int | None = None) -> str:
    """One cue as an SRT block, closed by the blank line that separates cues."""
    start = 1000 * (start_s if start_s is not None else index)
    return f"{index}\n{_srt_time(start)} --> {_srt_time(start + 900)}\n{text}\n\n"


def _srt_time(milliseconds: int) -> str:
    hours, rest = divmod(milliseconds, 3_600_000)
    minutes, rest = divmod(rest, 60_000)
    seconds, millis = divmod(rest, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


# ─── time conversion (2.3) ────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "timecode,expected",
    [
        ("00:00:00,000", 0),
        ("00:00:01,500", 1500),
        ("00:01:30,000", 90_000),
        ("01:01:01,001", 3_661_001),
        ("23:59:59,999", 86_399_999),
        ("00:01:02.500", 62_500),  # '.' instead of ','
        ("01:30,500", 90_500),  # missing hours field
        ("0:00:05,00", 5000),  # single-digit hours, 2-digit ms
    ],
)
def test_timecode_to_ms(timecode: str, expected: int) -> None:
    assert _srt_time_to_ms(timecode) == expected


def test_invalid_timecode_raises_domain_error() -> None:
    with pytest.raises(SubtitleFileError):
        _srt_time_to_ms("banana")


def test_fallback_chain_starts_with_bom_aware_utf8() -> None:
    assert FALLBACK_ENCODINGS[0] == "utf-8-sig"
    assert set(FALLBACK_ENCODINGS) >= {"utf-8", "cp1252", "cp1251", "latin-1"}


# ─── file level behaviour (2.3) ───────────────────────────────────────────────


def test_missing_file_raises_domain_error(tmp_path: Path) -> None:
    with pytest.raises(SubtitleFileError, match="not found"):
        SubtitleParserService.parse_srt(str(tmp_path / "nope.srt"))


def test_oversized_file_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    import app.subtitle_parser as module

    path = tmp_path / "big.srt"
    path.write_text(_cue(1, "Hello there."), encoding="utf-8")
    monkeypatch.setattr(module, "MAX_FILE_BYTES", 4)
    with pytest.raises(SubtitleFileError, match="safety limit"):
        SubtitleParserService.parse_srt(str(path))


def test_empty_file_raises_domain_error(tmp_path: Path) -> None:
    path = tmp_path / "empty.srt"
    path.write_bytes(b"")
    with pytest.raises(SubtitleFileError, match="empty"):
        SubtitleParserService.parse_srt(str(path))


def test_non_subtitle_content_raises(tmp_path: Path) -> None:
    path = tmp_path / "notes.srt"
    path.write_text("just prose, no timecodes at all", encoding="utf-8")
    with pytest.raises(SubtitleFileError, match="No cues"):
        SubtitleParserService.parse_srt(str(path))


# ─── fixture table (2.1 / 2.2 / 2.3) ─────────────────────────────────────────

FIXTURE_NAMES = [name for name, spec in SPECS.items() if spec.expect_kept is not None]


@pytest.mark.parametrize("name", sorted(FIXTURE_NAMES))
def test_fixture_expected_line_count(name: str) -> None:
    spec = SPECS[name]
    parsed = SubtitleParserService.parse_srt(str(_fixture(name)))
    assert parsed.report.cues_kept == spec.expect_kept, f"{name}: {parsed.lines}"
    assert parsed.report.cues_dropped == spec.expect_dropped


@pytest.mark.parametrize("name", sorted(FIXTURE_NAMES))
def test_fixture_line_numbers_are_gapless(name: str) -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture(name)))
    assert [line.line_index for line in parsed.lines] == list(range(1, len(parsed.lines) + 1))


@pytest.mark.parametrize("name", sorted(FIXTURE_NAMES))
def test_fixture_timings_are_sane_and_ordered(name: str) -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture(name)))
    starts = [line.start_time_ms for line in parsed.lines]
    assert starts == sorted(starts)
    for line in parsed.lines:
        assert 0 <= line.start_time_ms < line.end_time_ms


@pytest.mark.parametrize("name", sorted(FIXTURE_NAMES))
def test_fixture_text_is_cleaned_single_line(name: str) -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture(name)))
    for line in parsed.lines:
        assert "\n" not in line.raw_text
        assert "  " not in line.raw_text
        assert line.raw_text == line.raw_text.strip()
        assert "[" not in line.raw_text
        assert "{" not in line.raw_text
        assert "\u266a" not in line.raw_text


@pytest.mark.parametrize("name", sorted(FIXTURE_NAMES))
def test_fixture_declared_texts(name: str) -> None:
    spec = SPECS[name]
    if spec.expect_texts is None:
        pytest.skip("this fixture asserts counts only")
    parsed = SubtitleParserService.parse_srt(str(_fixture(name)))
    assert [line.raw_text for line in parsed.lines] == spec.expect_texts


def test_basic_fixture_exact_timings() -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture("basic_english.srt")))
    assert parsed.lines[0].start_time_ms == 1000
    assert parsed.lines[0].end_time_ms == 3500
    assert parsed.lines[1].line_index == 2
    assert parsed.lines[1].raw_text == "We should keep moving."


def test_cp1252_fixture_decodes_without_mojibake() -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture("windows_cp1252.srt")))
    assert parsed.report.encoding.replace("-", "").lower() in {"cp1252", "latin1", "windows1252"}
    joined = " ".join(line.raw_text for line in parsed.lines)
    assert "Caf\u00e9" in joined
    assert "\u00fc" in joined  # a real umlaut survived
    assert "\u00c3\u00a9" not in joined  # no mojibake


def test_bom_fixture_has_no_bom_in_text() -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture("utf8_bom.srt")))
    assert parsed.report.encoding == "utf-8-sig"
    assert all("\ufeff" not in line.raw_text for line in parsed.lines)


def test_malformed_fixture_is_survivable() -> None:
    """Broken timecode must not kill the file; a reversed interval must not store end<=start."""
    parsed = SubtitleParserService.parse_srt(str(_fixture("malformed.srt")))
    texts = [line.raw_text for line in parsed.lines]
    assert "First line survives." in texts
    assert "Reversed cues get a forced duration." in texts
    reversed_line = next(line for line in parsed.lines if line.raw_text.startswith("Reversed"))
    assert reversed_line.duration_ms == DEFAULT_CUE_DURATION_MS


# ─── parser details on inline content ────────────────────────────────────────


def test_noise_only_cue_is_dropped_and_numbering_closes_the_gap() -> None:
    content = "".join(
        [
            _cue(1, "Hello there."),
            _cue(2, "[APPLAUSE]"),
            _cue(3, "- General Kenobi."),
        ]
    )
    lines, report = SubtitleParserService.parse_srt_string(content)
    assert [line.raw_text for line in lines] == ["Hello there.", "General Kenobi."]
    assert [line.line_index for line in lines] == [1, 2]
    assert (report.cues_total, report.cues_kept, report.cues_dropped) == (3, 2, 1)


def test_cue_with_reversed_interval_gets_default_duration() -> None:
    content = f"1\n{_srt_time(5000)} --> {_srt_time(5000)}\nStuck cue.\n"
    lines, _ = SubtitleParserService.parse_srt_string(content)
    assert lines[0].duration_ms == DEFAULT_CUE_DURATION_MS


def test_multiline_cue_is_merged_into_one_row() -> None:
    content = _cue(1, "- You ready?\n- Born ready.")
    lines, _ = SubtitleParserService.parse_srt_string(content)
    assert len(lines) == 1
    assert lines[0].raw_text == "You ready? Born ready."


def test_all_cues_noise_returns_zero_lines_without_error() -> None:
    content = _cue(1, "[wind howling]") + _cue(2, "\u266a La la la \u266a")
    lines, report = SubtitleParserService.parse_srt_string(content)
    assert lines == []
    assert (report.cues_total, report.cues_kept) == (2, 0)


def test_crlf_and_lf_content_parse_identically() -> None:
    content = _cue(1, "One line.") + _cue(2, "Two lines.")
    lf, _ = SubtitleParserService.parse_srt_string(content)
    crlf, _ = SubtitleParserService.parse_srt_string(content.replace("\n", "\r\n"))
    assert [line.raw_text for line in lf] == [line.raw_text for line in crlf]


def test_speaker_labels_are_stripped_end_to_end() -> None:
    content = _cue(1, "WALTER: Say my name.") + _cue(2, "COACH:\nRun two laps.")
    lines, _ = SubtitleParserService.parse_srt_string(content)
    assert [line.raw_text for line in lines] == ["Say my name.", "Run two laps."]


def test_parse_file_returns_a_plain_list() -> None:
    lines = SubtitleParserService.parse_file(str(_fixture("basic_english.srt")))
    assert isinstance(lines, list)
    assert lines[0].raw_text == "The world is quiet here."


def test_forced_encoding_parameter_is_respected() -> None:
    parsed = SubtitleParserService.parse_srt(str(_fixture("windows_cp1252.srt")), encoding="cp1252")
    assert parsed.report.encoding == "cp1252"
    assert parsed.report.cues_kept == SPECS["windows_cp1252.srt"].expect_kept
