"""
Generate the step-2 test fixtures (``.srt`` files in several encodings).

Run once before the test-suite::

    python tests/data/make_fixtures.py

The files are *generated* instead of committed because cp1252/CRLF fixtures cannot
be stored as readable text in a UTF-8 repository. Every fixture carries its
expected parse result in :data:`FIXTURES`, so the tests assert against this table
(one source of truth) rather than against duplicated literals.

Cue timings are generated by a deterministic rule (start = 1000 + 1500*i ms,
duration 2500 ms) so the time-conversion assertions are stable.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

HERE = Path(__file__).resolve().parent


@dataclass(frozen=True)
class FixtureSpec:
    """One .srt fixture: how to write it and what the parser must return."""

    name: str
    encoding: str
    newline: str = "\n"
    texts: List[str] = field(default_factory=list)
    raw: Optional[str] = None
    expects_index: bool = True
    #: None means "structural edge case, assert loosely".
    expect_kept: Optional[int] = None
    expect_dropped: Optional[int] = None
    expect_texts: Optional[List[str]] = None
    note: str = ""


def _format_timecode(milliseconds: int) -> str:
    hours, rest = divmod(milliseconds, 3_600_000)
    minutes, rest = divmod(rest, 60_000)
    seconds, millis = divmod(rest, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


def build_content(texts: List[str], *, newline: str, expects_index: bool = True) -> str:
    """Render cue texts into an SRT document with generated timings.

    Cues are separated by an empty line on purpose: without it a parser reads the
    next index and timecode as part of the previous cue's text.
    """
    blocks: List[str] = []
    for index, text in enumerate(texts, start=1):
        start = 1000 + 1500 * (index - 1)
        end = start + 2500
        header = f"{index}{newline}" if expects_index else ""
        blocks.append(
            f"{header}{_format_timecode(start)} --> {_format_timecode(end)}{newline}{text}"
        )
    return (newline + newline).join(blocks) + newline


BASIC = FixtureSpec(
    name="basic_english.srt",
    encoding="utf-8",
    texts=[
        "The world is quiet here.",
        "We should keep moving.",
        "Are you coming with us?",
        "Not a chance in hell.",
        "Suit yourself.",
        "Wait for me!",
    ],
    expect_kept=6,
    expect_dropped=0,
    note="clean file, one line per cue",
)


def render_blocks(blocks: List[Tuple[int, int, str]], *, newline: str = "\n") -> str:
    """Render ``(start_ms, end_ms, text)`` triples with their own timings.

    Unlike :func:`build_content` this keeps hand-written timecodes, which is what a
    regression fixture needs: real rips do not space their cues on a metronome.
    """
    parts = [
        f"{index}{newline}{_format_timecode(start)} --> {_format_timecode(end)}{newline}{text}"
        for index, (start, end, text) in enumerate(blocks, start=1)
    ]
    return (newline + newline).join(parts) + newline


# A realistic SDH rip (T4.2): every rule of the sanitization matrix fires at least
# once, on real timings, with multi-line cues, forced newlines and HTML entities.
SDH_FULL_BLOCKS: List[Tuple[int, int, str]] = [
    (1000, 2400, "[TYPEWRITER DING]"),
    (
        2600,
        5100,
        '<font color="#E5E5E5">Let\'s apply ourselves to the</font>\n'
        '<font color="#E5E5E5">chemical equation, heisenberg.</font>',
    ),
    (5300, 6800, "[MUSIC PLAYING]"),
    (
        7000,
        10400,
        "\u266a Bound for the shine and the foam \u266a\n\u266a Bound for the shine and the foam \u266a",
    ),
    (10600, 12100, "JESSE: Yo, Mr. White."),
    (12300, 14000, "MR. WHITE: You're my partner."),
    (14200, 15400, "WALTER, JR.: Grandpa?"),
    (15600, 17200, "[phone vibrating] Hello?"),
    (17400, 18200, "(GUNSHOT)"),
    (18400, 20600, "(sighs) I'm tired of this."),
    (20800, 22500, "DON'T: Get out of here!"),
    (22700, 24300, "Time: 5 min"),
    (24500, 27100, "- We need to cook.\n- I'm busy."),
    (27300, 29000, "{\\an8}Watch the temperature.{\\pos(20, 200)}"),
    (29200, 30100, "<i>(GROANS)</i>"),
    (30300, 32800, "Look at me... I'm the danger."),
    (33000, 35400, '"Fire off.\nPull trigger."'),
    (35600, 37200, "The tank [BOOM] went sideways."),
    (37400, 39300, "www.site.com:8080 is down."),
    (39500, 41800, "I said, \u201cI\u2019m sorry.\u201d \u2014 really."),
    (42000, 44100, "COACH:\nRun two laps."),
    (44300, 45600, "\u2014Good morning."),
    (45800, 47900, "Hey.   Wake   up."),
    (48100, 49000, "[APPLAUSE]"),
    (49200, 51300, "<b>Nothing</b> is going to plan. Don't (again!) push me."),
    (51500, 53400, "No half measures."),
]

SDH_FULL = FixtureSpec(
    name="sdh_full.srt",
    encoding="utf-8",
    raw=render_blocks(SDH_FULL_BLOCKS),
    expect_kept=20,
    expect_dropped=6,
    expect_texts=[
        "Let's apply ourselves to the chemical equation, heisenberg.",
        "Yo, Mr. White.",
        "You're my partner.",
        # Known limitation, pinned on purpose: the label regex has no ',' in its
        # character class, so "WALTER, JR.:" survives. Changing this line means the
        # rule changed -- see the §8 decision log of the task board.
        "WALTER, JR.: Grandpa?",
        "Hello?",
        "(sighs) I'm tired of this.",
        "Get out of here!",
        "Time: 5 min",
        "We need to cook. I'm busy.",
        "Watch the temperature.",
        "Look at me... I'm the danger.",
        '"Fire off. Pull trigger."',
        "The tank went sideways.",
        "www.site.com:8080 is down.",
        'I said, "I\'m sorry." - really.',
        "Run two laps.",
        "Good morning.",
        "Hey. Wake up.",
        "Nothing is going to plan. Don't (again!) push me.",
        "No half measures.",
    ],
    note="26-cue SDH rip: regression baseline for the whole sanitization matrix",
)

SDH_NOISE = FixtureSpec(
    name="sdh_noise.srt",
    encoding="utf-8",
    texts=[
        "<i>Put it down, Walter.</i>",
        "[door creaks] Where is he?",
        r"{\an8}You can't[bleep]be serious",
        "(CHUCKLES) We can do it (together).",
        "(GROANS)\n\u266a Ring of fire \u266a",
        "WALTER: Put it down.",
        "\u2014Hey.\n-Wake up.",
        "[Upbeat music]",
    ],
    expect_kept=6,
    expect_dropped=2,
    expect_texts=[
        "Put it down, Walter.",
        "Where is he?",
        "You can't be serious",
        "We can do it (together).",
        "Put it down.",
        "Hey. Wake up.",
    ],
    note="HTML + ASS + SDH brackets + ALL-CAPS parens + music + speaker label + dashes",
)

SPEAKER_LABELS = FixtureSpec(
    name="speaker_labels.srt",
    encoding="utf-8",
    texts=[
        "JESSE: Yo, Mr. White",
        "MAN ON TV: Breaking news tonight",
        "OFFICER 1: Clear the area",
        "COACH:\nPractice starts at six.",
        "DR. SMITH: The results are in",
    ],
    expect_kept=5,
    expect_dropped=0,
    expect_texts=[
        "Yo, Mr. White",
        "Breaking news tonight",
        "Clear the area",
        "Practice starts at six.",
        "The results are in",
    ],
    note="labels with digits, spaces, dots and a label alone on its line",
)

MUSIC_AND_ELLIPSIS = FixtureSpec(
    name="music_and_ellipsis.srt",
    encoding="utf-8",
    texts=[
        "\u266a Silent night \u266a",
        "# Silent night #",
        "\u266a Fair is foul, and foul is fair \u266a\nHover through the fog and filthy air.",
        'I said #13-37, not "hot".',
        "Wait...",
    ],
    expect_kept=3,
    expect_dropped=2,
    expect_texts=[
        "Hover through the fog and filthy air.",
        'I said #13-37, not "hot".',
        "Wait...",
    ],
    note="sung lines dropped, hashtag-as-text and ellipses preserved",
)

WINDOWS_CP1252 = FixtureSpec(
    name="windows_cp1252.srt",
    encoding="cp1252",
    newline="\r\n",
    texts=[
        "Caf\u00e9 \u2014 cr\u00e8me br\u00fbl\u00e9e",
        "Gr\u00fc\u00dfe aus M\u00fcnchen",
        "Se\u00f1or, \u00bfdonde est\u00e1 la estaci\u00f3n?",
        "Delicious cr\u00e8me br\u00fbl\u00e9e, non?",
    ],
    expect_kept=4,
    expect_dropped=0,
    expect_texts=[
        "Caf\u00e9 - cr\u00e8me br\u00fbl\u00e9e",
        "Gr\u00fc\u00dfe aus M\u00fcnchen",
        "Se\u00f1or, \u00bfdonde est\u00e1 la estaci\u00f3n?",
        "Delicious cr\u00e8me br\u00fbl\u00e9e, non?",
    ],
    note="legacy single-byte encoding + CRLF, no mojibake allowed",
)

UTF8_BOM = FixtureSpec(
    name="utf8_bom.srt",
    encoding="utf-8-sig",
    newline="\r\n",
    texts=[
        "It begins at last.",
        "Nothing but speech here.",
        "End of the reel.",
    ],
    expect_kept=3,
    expect_dropped=0,
    note="BOM must not leak into the first cue",
)

NO_INDEX = FixtureSpec(
    name="no_index_numbers.srt",
    encoding="utf-8",
    expects_index=False,
    texts=[
        "Nobody numbers these days.",
        "The parser still finds the cues.",
    ],
    expect_kept=2,
    expect_dropped=0,
    note="cue index lines are optional",
)

MALFORMED = FixtureSpec(
    name="malformed.srt",
    encoding="utf-8",
    raw=(
        "1\n"
        "00:00:01,000 --> 00:00:02,000\n"
        "First line survives.\n"
        "\n"
        "2\n"
        "00:00:99,999 --> bogus\n"
        "This block has an unparseable timecode.\n"
        "\n"
        "3\n"
        "00:00:03,000 --> 00:00:02,000\n"
        "Reversed cues get a forced duration.\n"
    ),
    expect_kept=None,
    expect_dropped=None,
    note="fault tolerance: broken timecode + reversed interval",
)

# Maximal-noise corpus for the manual acceptance run (T6.1): the shapes a real rip
# actually carries, including forms the matrix fixtures do not model -- nested and
# unclosed tags, ASS override blocks, multi-word SDH remarks, HTML entities that must
# *not* be decoded, symbol-only cues, tabs, non-breaking spaces and hard ``\N`` breaks.
# Timings ascend so pysrt stays the engine: this file stresses the cleaner, not the reader.
STRESS_BLOCKS: List[Tuple[int, int, str]] = [
    (1000, 3400, "<i><b>[AIR HISS]</b></i>"),
    (3500, 6200, '<font size="16"><font color="#FFFF00">Previously on the show.</font></font>'),
    (6300, 8900, "We're done here.\n<i>Go home.</i>"),
    (9000, 11500, "[DOOR OPENS]"),
    (11600, 14100, "[car engine revving] He's pulling out!"),
    (14200, 16800, "(GUNSHOT COCKING) Get down!"),
    (16900, 19400, "(ALL EXCLAIM IN SURPRISE) No way."),
    (19500, 22100, "(ne переведено) Что это было?"),
    (22200, 24700, "Chapter (No. 5) begins now."),
    (24800, 27300, "He (Mr. French) never showed up."),
    (27400, 29900, "Hello? Hello?[phone rings"),
    (30000, 32500, r"{\an8}{\fad(200,200)}Target acquired.{\r}"),
    (32600, 35100, r"{\b1}Wait for my signal{\b0}, then move."),
    (35200, 37700, r"Copy that. {\i1}Standing by.{\i0}"),
    (37800, 40300, "&quot;Stand easy,&quot; he said."),
    (40400, 42900, "It&#39;s a trap &mdash; fall back!"),
    (43000, 45500, "Nothing &amp; nothing else."),
    (45600, 48100, "<i>This sentence never closes its tag."),
    (48200, 50700, "Radio says &lt;unknown&gt;."),
    (50800, 53300, "[BLEEP] What the [bleep] was that?"),
    (53400, 55900, "SARAH: I don't take orders from you."),
    (56000, 58500, "DAVID: Then you're on your own."),
    (58600, 61100, "- I know that."),
    (61200, 63700, "\u2014 And I'm staying."),
    (63800, 66300, ">> Watch your six."),
    (66400, 68900, ">>>\tCopy."),
    (69000, 71500, "MAN ON RADIO: Hold position."),
    (71600, 74100, "OFFICER 2: Move it, move it."),
    (74200, 76700, "OLD MAN:\nYou don't look so good."),
    (76800, 79300, "NARRATOR: Previously, on the island."),
    (79400, 81900, "KID: Why? Just... why?"),
    (82000, 84500, "MOM: Because I said so."),
    (84600, 87100, "JESS: It's not about you."),
    (87200, 89700, "Jo: Neither is this."),
    (89800, 92300, "Wait. Shhh... listen."),
    (92400, 94900, "-Left, then right."),
    (95000, 97500, "-Left again. -Go!"),
    (97600, 100100, "\u266a We'll meet again \u266a\n\u266a Don't keep us waiting \u266a"),
    (100200, 102700, "[SOULFUL BALLAD CONTINUES]"),
    (102800, 105300, "\u266a For he's a jolly good fellow."),
    (105400, 107900, "Keep the change."),
    (108000, 110500, "I said, keep the change."),
    (110600, 113100, "Are you listening to me?"),
    (113200, 115700, "Loud and clear."),
    (115800, 118300, "Then act like it."),
    (118400, 120900, "\u00a0See\u00a0you\u00a0there.\u00a0"),
    (121000, 123500, "It\u2019s 2\u202fA.M. \u2014 don\u2019t call me."),
    (123600, 126100, "\u00ab\u041e\u0434\u0438\u043d \u0437\u0430 \u0432\u0441\u0435\u00bb \u2014 said the captain."),
    (126200, 128700, "Meet me at 12:30 on 05.06.2026."),
    (128800, 131300, "Call 555-0199, extension 12."),
    (131400, 133900, "www.site.com:8080/login is down."),
    (134000, 136500, "Route 66, mile #13-37."),
    (136600, 139100, "#blessed #13-37 and #hashtag."),
    (139200, 141700, "She said \u201cmaybe\u201d \u2014 which means no."),
    (141800, 144300, "One more thing\u2026"),
    (144400, 146900, "A\tB\tC  tabs  here."),
    (147000, 149500, "Ladies and gentlemen\u2026\u2026\u2026"),
    (149600, 152100, "C\u2019est la vie, non?"),
    (152200, 154700, "Это не по-английски будет? Are you serious?"),
    (154800, 157300, "Mixed: текст и text together."),
    (157400, 159900, "!!!"),
    (160000, 162500, "---"),
    (162600, 165100, "\u266a\u266a\u266a"),
    (165200, 167700, "<i></i>"),
    (167800, 170300, r"{\an8}"),
    (170400, 172900, "["),
    (173000, 175500, "]"),
    (175600, 178100, "\u2026"),
    (178200, 180700, "Room 0"),
    (180800, 183300, "[MUSIC PLAYING]\n[APPLAUSE]"),
    (183400, 185900, "(SIGHS)\n(GROANS)"),
    (186000, 188500, "   \t  "),
    (188600, 191100, "&nbsp;&nbsp;"),
    (191200, 193700, "<br/>"),
    (193800, 196300, ".. :: .."),
    (196400, 198900, "First line\\Nsecond hard break."),
    (199000, 201500, "Second subtitle track:\\N- Yes?\\N- No."),
    (201600, 204100, "Captain's log, stardate 41152.7."),
    (204200, 206700, "A-OK. B-plus. C-minus."),
    (206800, 209300, "T-800 is back. Be there in 5 min."),
    (209400, 211900, "It's a 100%, no joke."),
    (212000, 214500, "U.S.A. vs. USSR, round two."),
    (214600, 217100, "He's Dr. Smith, not Mr. Smith."),
    (217200, 219700, "Wait... no, wait... I get it."),
    (219800, 222300, "No! No no no. Yes."),
    (222400, 224900, "Hank? Hank!\nHANK: Yeah, yeah."),
    (225000, 227500, "One, two, three... go!\n-Go!\n>>Go!"),
    (227600, 230100, "[CROWD CHEERING]\nANNOUNCER: Ladies and gentlemen!"),
    (230200, 232700, "Line one.\nLine two.\nLine three."),
    (232800, 235300, "That's all, folks."),
]

STRESS = FixtureSpec(
    name="stress_realworld.srt",
    encoding="utf-8",
    raw=render_blocks(STRESS_BLOCKS),
    #: Counts measured by the T6.1 manual run (see the task board, §7). ``expect_texts``
    #: stays empty on purpose: this corpus is the leftovers' oracle (§6 dirt query),
    #: pinning 71 literals would freeze the known imperfections as "desired output".
    #: 71/19 since D18: a leading "#" no longer drops the whole line.
    expect_kept=71,
    expect_dropped=19,
    expect_texts=None,
    note="90-cue T6.1 stress corpus: counts only, real-text oracle is the §6 dirt query",
)

FIXTURES = [
    BASIC,
    SDH_NOISE,
    SDH_FULL,
    SPEAKER_LABELS,
    MUSIC_AND_ELLIPSIS,
    WINDOWS_CP1252,
    UTF8_BOM,
    NO_INDEX,
    MALFORMED,
    STRESS,
]


def content_of(spec: FixtureSpec) -> str:
    if spec.raw is not None:
        return spec.raw.replace("\n", spec.newline)
    return build_content(spec.texts, newline=spec.newline, expects_index=spec.expects_index)


def write_fixtures(directory: Path = HERE) -> List[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for spec in FIXTURES:
        path = directory / spec.name
        # utf-8-sig prepends the BOM on encode; every other codec writes plain bytes.
        path.write_bytes(content_of(spec).encode(spec.encoding))
        written.append(path)
    return written


def main(argv: Optional[List[str]] = None) -> int:
    directory = Path(argv[0]) if argv and argv[0] else HERE
    for path in write_fixtures(directory):
        print(f"wrote {path.relative_to(Path.cwd()) if path.is_relative_to(Path.cwd()) else path}"
              f" ({path.stat().st_size} bytes)")
    print(f"{len(FIXTURES)} fixtures in {directory}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
